blank_issues_enabled: true

contact_links:
  - name: Questions & Discussions ðŸ’¬
    url: https://github.com/SamErde/DLLPickle/discussions
    about: Please use GitHub discussions for any questions or suggestions.
  - name: Documentation ðŸ“š
    url: https://day3bits.com/DLLPickle
    about: Documentation for the DLLPickle project.
  - name: ReadTheDocs ðŸ“– (Alternate/Backup Documentation Site)
    url: https://dllpickle.readthedocs.io/en/latest/
    about: ReadTheDocs for the DLLPickle project.
