blank_issues_enabled: false

contact_links:
  - name: Questions & Discussions ğŸ’¬
    url: https://github.com/SamErde/DLLPickle/discussions
    about: Please use GitHub discussions for any questions.
  - name: Documentation ğŸ“š
    url: https://day3bits.com/DLLPickle
    about: Documentation for the DLLPickle project.
  - name: ReadTheDocs ğŸ“– (Alternate/Backup Documentation Site)
    url: https://dllpickle.readthedocs.io/en/latest/
    about: ReadTheDocs for the DLLPickle project.
#  - name: Basic FAQs â“
#    url: https://github.com/SamErde/DLLPickle/wiki/FAQs
#    about: Answers to the Basic Frequently Asked Questions
