# https://help.github.com/en/actions/automating-your-workflow-with-github-actions
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/virtual-environments-for-github-hosted-runners
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#using-a-specific-shell
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-powershell
# https://github.com/actions/upload-artifact#where-does-the-upload-go
name: Build Module (Windows)

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    paths:
      - "src/**"
      - ".github/workflows/Build Module - Windows.yml"
  push:
    branches:
      - main
    paths:
      - "src/**"
      - ".github/workflows/Build Module - Windows.yml"

permissions:
  contents: read

jobs:

  build:

    name: Test and Build Module (Windows)
    runs-on: windows-latest
    strategy:
      fail-fast: false
    steps:

    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
      with:
        egress-policy: audit

    - name: Check out repository
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

    - name: Cache PowerShell modules
      uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c # v3.5.0
      with:
        path: |
          ~\Documents\PowerShell\Modules
          ~\Documents\WindowsPowerShell\Modules
        key: ${{ runner.os }}-psmodules-${{ hashFiles('src/DLLPickle.build.ps1', '.github/workflows/Actions_Bootstrap.ps1') }}

    - name: Bootstrap
      shell: pwsh
      run: ./.github/workflows/Actions_Bootstrap.ps1

    - name: Test and Build
      shell: pwsh
      run: Invoke-Build -File ./src/DLLPickle.Build.ps1

    - name: Upload pester results
      if: always() # Ensure this step runs even if prior steps fail
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      with:
        name: pester-results
        path: ./src/Artifacts/TestOutput
        if-no-files-found: warn

    - name: Upload zip module archive build
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      with:
        name: zip-archive
        path: ./src/Archive
        if-no-files-found: warn
