# https://help.github.com/en/actions/automating-your-workflow-with-github-actions
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/virtual-environments-for-github-hosted-runners
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#using-a-specific-shell
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-powershell
# https://github.com/actions/upload-artifact#where-does-the-upload-go
name: Build Module (Windows)

on:
  workflow_call:
  workflow_dispatch:
  #pull_request:
  #  paths:
  #    - "src/**"
  #    - ".github/workflows/Build Module - Windows.yml"
  #push:
  #  branches:
  #    - main
  #  paths:
  #    - "src/**"
  #    - ".github/workflows/Build Module - Windows.yml"

permissions:
  contents: read

jobs:

  build:

    name: Test and Build Module (Windows)
    runs-on: windows-latest
    strategy:
      fail-fast: false
    steps:

    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
      with:
        egress-policy: audit

    - name: Check out repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Cache PowerShell modules
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
      with:
        path: |
          ~\Documents\PowerShell\Modules
          ~\Documents\WindowsPowerShell\Modules
        key: ${{ runner.os }}-psmodules-${{ hashFiles('src/DLLPickle.Build.ps1', '.github/workflows/Actions_Bootstrap.ps1') }}

    - name: Bootstrap
      shell: pwsh
      run: ./.github/ci-scripts/Actions_Bootstrap.ps1

    - name: Test and Build
      shell: pwsh
      run: Invoke-Build -File ./build/DLLPickle.Build.ps1

    - name: Upload pester results
      if: always() # Ensure this step runs even if prior steps fail
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      with:
        name: pester-results
        path: ./artifacts/TestOutput
        if-no-files-found: warn

    - name: Upload zip module archive build
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      with:
        name: zip-archive
        path: ./archive
        if-no-files-found: warn
