name: CI Build & Test
on:
  pull_request:
    branches: [main]
    paths:
      - 'src/DLLPickle.Build/**'
      - 'packages.lock.json'
      - '.github/workflows/Build and Test Packages.yml'

permissions:  # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  build-and-test:
    name: ğŸš€ Build and Test
    runs-on: windows-latest
    permissions:
      contents: read
      pull-requests: write # Required for dependency review comments

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: ğŸ‘· Setup MSBuild
        uses: microsoft/setup-msbuild@6fb02220983dee41ce7ae257b6f4d8f9bf5ed4ce # v2.0.0

      - name: ğŸ§‘â€ğŸ’» Setup .NET
        uses: actions/setup-dotnet@baa11fbfe1d6520db94683bd5c7a3818018e4309 # v5.1.0
        with:
          dotnet-version: '8.0.x'

      - name: ğŸ“¦ Restore dependencies
        run: dotnet restore src/DLLPickle.Build/DLLPickle.csproj --force-evaluate
        shell: pwsh

      - name: ğŸ—ï¸ Build
        run: dotnet build src/DLLPickle.Build/DLLPickle.csproj --configuration Release --no-restore

      - name: ğŸ›¡ï¸ Dependency Review
        if: github.event_name == 'pull_request'
        uses: actions/dependency-review-action@3c4e3dcb1aa7874d2c16be7d79418e9b7efd6261 # v4.8.2
        with:
          fail-on-severity: high
